# Generated by Django 6.0.3 on 2026-04-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boats", "0002_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="boat",
            name="luxury_subcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("crewed_yacht", "Crewed Yacht"),
                    ("private_charter", "Private Charter"),
                    ("sunset_cruise", "Sunset Cruise"),
                ],
                max_length=30,
            ),
        ),
    ]
