# Generated by Django 6.0.3 on 2026-03-22 18:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boats", "0002_wishlist"),
        ("reviews", "0002_alter_review_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "boat")},
        ),
    ]
